name: climb_it 
description: A bouldering companion app to view available routes and manage completed routes in local bouldering gym.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  cached_network_image: ^3.2.3
  video_player: ^2.6.1
  flutter_phoenix: ^1.1.1
  flutter_settings_screens: ^0.3.3-null-safety+2
  fl_chart: ^0.63.0
  geolocator: ^9.0.2
  customizable_counter: ^1.0.4 #Might not be needed 
  shared_preferences: ^2.1.2
  flutter_switch: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true