name: climb_it 
description: A bouldering companion app to view available routes and manage completed routes in local bouldering gym.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  cached_network_image: ^3.2.3
  video_player: ^2.6.1
  flutter_phoenix: ^1.1.1
  flutter_settings_screens: ^0.3.3-null-safety+2
  fl_chart: ^0.63.0
  geolocator: ^9.0.2
  shared_preferences: ^2.1.2
  flutter_switch: ^0.3.2
  image_picker: ^0.8.9
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.13.1
  customizable_counter: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  assets:
    - assets/
  uses-material-design: true